// NOCHILL Product Catalog — 50 products + 5 bundles
// Sourced from product briefs in /Desktop/product-lab/products/briefs/
// Each entry maps to a WAT.md brief with full Shopify copy and ICP data

export type PlanningStatus = 'draft' | 'building' | 'built' | 'live'
export type ICP = '1' | '2' | 'both'
export type ProductTrack =
  | 'icp2-entry'
  | 'icp2-mid'
  | 'icp1-tier3'
  | 'icp1-tier4'
  | 'framework'
  | 'bundle'

export interface ProductPlanEntry {
  code: string
  name: string
  subtitle: string
  price: number
  priceRange?: string
  icp: ICP
  icpLabel: string
  painPoints: string[]
  problemSolved: string
  transformation: string
  shadowFears: string[]
  paidsStream: string
  track: ProductTrack
  description: string
  shopifyCopy: string
  productType: 'digital_product' | 'course' | 'coaching' | 'service' | 'bundle'
  audienceLevel: 'beginner' | 'established' | 'contentpreneur'
  ladderPosition: 'entry' | 'core' | 'premium' | 'elite'
  isBundle?: boolean
}

export const PRODUCT_CATALOG: ProductPlanEntry[] = [
  // ─── ICP 2 ENTRY TIER ───────────────────────────────────────
  {
    code: 'P01',
    name: 'The Hook Bible',
    subtitle: '333 hooks engineered to stop the scroll in South Africa',
    price: 497,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: [
      'Content gets under 500 views consistently',
      'Spends hours on content that nobody watches',
      'Knows hooks are important but can\'t write them',
      'Posts and gets silence',
    ],
    problemSolved: 'No system for writing high-retention opening lines that make SA audiences stop scrolling',
    transformation: 'From content nobody watches → 333 tested hooks for every niche, platform, and content type',
    shadowFears: ['SF5 — Invisible Labor', 'SF6 — Platform Dependency'],
    paidsStream: 'products',
    track: 'icp2-entry',
    description: '333-hook swipe file built specifically for SA creators. Organised by niche, platform, and content type. The single biggest lever for reach growth.',
    shopifyCopy: `You spend hours creating content. You post it. Silence.\n\nNot because your content is bad. Because nobody stopped to watch it.\n\nThe Hook Bible is 333 engineered opening lines — built for SA creators, tested on SA audiences — organised by niche, platform, and content type.\n\nNo generic "content creation tips." These hooks are built for the creator who knows what they\'re doing but keeps getting 200 views.\n\nR497. 333 hooks. The scroll stops here.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'beginner',
    ladderPosition: 'entry',
  },
  {
    code: 'P02',
    name: 'Niche in 24 Hours',
    subtitle: 'Find the one profitable niche you\'ll actually stick to — by tomorrow',
    price: 297,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: [
      'Posting everything, growing nothing',
      'Doesn\'t know what to specialise in',
      'Algorithm doesn\'t know who to show content to',
      'No clear positioning',
    ],
    problemSolved: 'Creates content without knowing who it\'s for or what it stands for',
    transformation: 'From scattered creator → clear niche with content direction in 24 hours',
    shadowFears: ['SF4 — Wrong Path Terror', 'SF3 — Imposter Syndrome'],
    paidsStream: 'products',
    track: 'icp2-entry',
    description: '6-exercise niche system that uses what you already know, what you love, and what people are already paying for. SA-specific niche validation.',
    shopifyCopy: `You\'ve been posting for 6 months. You don\'t know what you stand for.\n\nPosting everything means the algorithm doesn\'t know who to show you to. And neither does any brand.\n\nNiche in 24 Hours is 6 exercises that lock your niche — not based on trends, but based on what you know, what you love, and what SA audiences are already paying for.\n\nYou won\'t need 3 months of trial and error. You need 24 hours and a pen.\n\nR297. One niche. By tomorrow.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'beginner',
    ladderPosition: 'entry',
  },
  {
    code: 'P03',
    name: 'The Content Calendar System',
    subtitle: 'Plan 30 days of content in one afternoon — and actually post it',
    price: 297,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: [
      'Posts randomly with no plan',
      'Runs out of ideas mid-week',
      'Inconsistent because there\'s no system',
    ],
    problemSolved: 'No content planning system that accounts for SA load shedding, real life, and the 4E ratio',
    transformation: 'From chaotic posting → 30-day calendar with balanced content types and backup plans',
    shadowFears: ['SF7 — Time Anxiety', 'SF5 — Invisible Labor'],
    paidsStream: 'products',
    track: 'icp2-entry',
    description: '30/60/90-day calendar templates built on the 4E ratio (3:3:3:1). Load-shedding backup schedule. Weekly review protocol.',
    shopifyCopy: `Consistency is not motivation. Consistency is a system.\n\nIf you post when you feel like it, you\'ll post 3 times a month and wonder why you\'re not growing.\n\nThe Content Calendar System gives you 30/60/90-day templates built on the 4E ratio — the content balance that grows audiences and makes money at the same time.\n\nIncludes a load-shedding backup schedule, because this is South Africa.\n\nR297. One afternoon to plan. One month to post.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'beginner',
    ladderPosition: 'entry',
  },
  {
    code: 'P04',
    name: 'No Content Ideas',
    subtitle: 'Never run out of content ideas again — using only 3 inputs from your life',
    price: 297,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: [
      'Stares at blank screen, can\'t think of what to post',
      'Ideas run out after week 2',
      'Copies other creators because they\'re out of ideas',
    ],
    problemSolved: 'No sustainable idea generation system rooted in their own life and niche',
    transformation: 'From blank screen → 90-day idea bank from 3 personal inputs',
    shadowFears: ['SF5 — Invisible Labor', 'SF3 — Imposter Syndrome'],
    paidsStream: 'products',
    track: 'icp2-entry',
    description: '90-day idea generation system. 3 inputs (expertise, audience pain, SA trends) × matrix = unlimited niche-aligned content ideas.',
    shopifyCopy: `If you\'re copying other creators because you ran out of ideas — you don\'t have a creativity problem. You have a system problem.\n\nNo Content Ideas is a 90-day idea generation system built on 3 inputs that live in your own life: what you know, what your audience is asking, and what SA audiences are paying attention to right now.\n\nOne afternoon to build the system. 90 days of content direction.\n\nR297. Three inputs. No more blank screens.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'beginner',
    ladderPosition: 'entry',
  },
  {
    code: 'P05',
    name: 'The Broke Creator Checklist',
    subtitle: '25 questions that show you exactly why you\'re creating but not earning',
    price: 297,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: [
      'Creating consistently but earning nothing',
      'Doesn\'t know where the system is broken',
      'Feels like they\'re doing everything right but getting nowhere',
    ],
    problemSolved: 'No diagnostic tool to identify which part of the creator business is actually broken',
    transformation: 'From confusion → clear diagnosis of exactly what\'s blocking income, in 25 questions',
    shadowFears: ['SF2 — Generational Poverty', 'SF1 — Wasted Life'],
    paidsStream: 'products',
    track: 'icp2-entry',
    description: '25-point creator business audit. Covers: niche, content, platform, monetisation, mindset. Tells you where the gap is.',
    shopifyCopy: `You\'re creating. You\'re consistent. You\'re still broke.\n\nThat means something in the system is broken — and it\'s not you.\n\nThe Broke Creator Checklist is 25 diagnostic questions across 5 categories: niche clarity, content system, platform fit, monetisation readiness, and mindset. By question 25, you\'ll know exactly what\'s blocking your income.\n\nNot motivation. Not a pep talk. A diagnosis.\n\nR297. 25 questions. The answer you\'ve been looking for.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'beginner',
    ladderPosition: 'entry',
  },
  {
    code: 'P06',
    name: 'Caption Formula Pack',
    subtitle: '10 formulas + 50 templates for captions that make people stop, read, and act',
    price: 497,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: [
      'Writes captions as an afterthought',
      'Gets views but no engagement or action',
      'Doesn\'t know how to write a CTA that works',
    ],
    problemSolved: 'No structured approach to caption writing — the copy that converts views to followers, followers to buyers',
    transformation: 'From weak captions → 10 formula-driven templates that drive engagement and action',
    shadowFears: ['SF5 — Invisible Labor', 'SF6 — Platform Dependency'],
    paidsStream: 'products',
    track: 'icp2-entry',
    description: '10 caption formulas + 50 fill-in templates across 5 content types. SA-specific examples throughout.',
    shopifyCopy: `The reel gets the view. The caption gets the follow, the DM, the sale.\n\nMost creators treat captions as an afterthought. That\'s why their views don\'t convert.\n\nThe Caption Formula Pack gives you 10 formula-driven caption structures and 50 fill-in templates — for educational posts, story posts, opinion posts, proof posts, and CTAs.\n\nSA-specific examples. No generic "best caption tips."\n\nR497. 10 formulas. 50 templates. Your captions start working.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'beginner',
    ladderPosition: 'entry',
  },
  {
    code: 'P07',
    name: 'First Brand Deal Script',
    subtitle: '5 word-for-word scripts for every stage of your first brand deal negotiation',
    price: 297,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: [
      'Freezes when a brand DMs',
      'Undersells in first response',
      'Doesn\'t know how to negotiate or counter',
    ],
    problemSolved: 'No response system for brand DMs — the moment that determines your rate permanently',
    transformation: 'From panicking in DMs → 5 scripts that handle every brand scenario without underselling',
    shadowFears: ['SF3 — Imposter Syndrome', 'SF5 — Invisible Labor'],
    paidsStream: 'deals',
    track: 'icp2-entry',
    description: '5 WhatsApp/DM scripts: first approach, budget probe, counter-offer, exclusivity, follow-up. SA brand deal context.',
    shopifyCopy: `The first thing you say to a brand sets your rate — forever.\n\nAgencies file your responses. They share notes. What are they filing about you?\n\nFirst Brand Deal Script is 5 word-for-word scripts for every stage of a brand deal: first approach, budget probing, counter-offer, exclusivity negotiation, follow-up. SA-specific. WhatsApp-ready.\n\nI went from R750 to R100,000 per deal. The difference was the script, not the following.\n\nR297. 5 scripts. Never freeze again.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'beginner',
    ladderPosition: 'entry',
  },
  {
    code: 'P08',
    name: 'SARS Creator Income Guide',
    subtitle: 'What SARS knows about your Paystack — and what you need to do about it',
    price: 497,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: [
      'Earning online but ignoring SARS',
      'Doesn\'t know if they need to register',
      'Afraid of a surprise tax bill',
    ],
    problemSolved: 'No SA-specific guide to digital income tax compliance for creators earning under R1 million',
    transformation: 'From SARS avoidance → clear understanding of obligations and a compliance plan',
    shadowFears: ['SF2 — Generational Poverty', 'SF4 — Wrong Path Terror'],
    paidsStream: 'products',
    track: 'icp2-entry',
    description: 'SA-specific digital income tax basics. Who must register, what to declare, basic provisional tax intro.',
    shopifyCopy: `SARS knows about your Paystack. The question is whether you know about SARS.\n\nI received a R207,879 tax letter — not a fine, but tax on income I legitimately earned but categorised incorrectly.\n\nThe SARS Creator Income Guide covers SA digital income tax basics: who must register, what counts as taxable income, basic provisional tax, and what your Paystack history means at tax season.\n\nNot a lecture. A guide. Written in the language of someone who\'s already made the expensive mistakes.\n\nR497. SA-specific. SARS-ready.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'beginner',
    ladderPosition: 'entry',
  },
  {
    code: 'P09',
    name: 'The Algorithm Myth',
    subtitle: 'Everything you believe about the algorithm is wrong — here\'s what actually works',
    price: 297,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: [
      'Chasing trends instead of building an audience',
      'Believes algorithm is the enemy',
      'Gets 1 viral post then back to 0',
    ],
    problemSolved: 'Misunderstanding of how platforms actually distribute content — chasing the algorithm instead of understanding it',
    transformation: 'From algorithm anxiety → understanding the 4 real signals platforms reward and building for them',
    shadowFears: ['SF6 — Platform Dependency', 'SF4 — Wrong Path Terror'],
    paidsStream: 'products',
    track: 'icp2-entry',
    description: '30-page myth-bust guide. The 4 signals platforms actually reward. Why views aren\'t the metric that matters.',
    shopifyCopy: `The algorithm is not your enemy. Your misunderstanding of it is.\n\nThe Algorithm Myth busts 7 beliefs about social media platforms that keep SA creators grinding without growing — and replaces them with the 4 signals platforms actually reward: watch time, saves, shares, and returning viewers.\n\nOne viral post followed by nothing means the algorithm was never the problem.\n\nR297. 30 pages. The algorithm stops being the enemy.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'beginner',
    ladderPosition: 'entry',
  },
  {
    code: 'P10',
    name: '780K Hooks',
    subtitle: 'The advanced hook vault — 780,000-reach hooks analysed and reverse-engineered',
    price: 497,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: [
      'Writes hooks but they\'re not working',
      'Inconsistent reach — sometimes viral, usually not',
      'Doesn\'t understand why some hooks work and others don\'t',
    ],
    problemSolved: 'No data-backed hook writing framework — guessing instead of engineering attention',
    transformation: 'From hook guessing → 100+ reverse-engineered hooks from 780K+ reach content with the pattern decoded',
    shadowFears: ['SF5 — Invisible Labor', 'SF6 — Platform Dependency'],
    paidsStream: 'products',
    track: 'icp2-entry',
    description: '100+ hooks from high-performing content dissected and reformatted. The R×A×C×U^B formula applied to real examples.',
    shopifyCopy: `One reel: 47 views. Same creator, same week, same niche — another reel: 2.3 million views.\n\nThe difference was 8 words in the opening.\n\n780K Hooks is 100+ opening lines from verified high-performing content — each one decoded with the R×A×C×U^B formula so you understand not just what worked, but why.\n\nThis is not a swipe file. It\'s an engineering class disguised as a swipe file.\n\nR497. 100+ hooks decoded. The pattern yours forever.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'beginner',
    ladderPosition: 'entry',
  },

  // ─── ICP 2 MID TIER ───────────────────────────────────────
  {
    code: 'P11',
    name: 'Creator Starter System',
    subtitle: 'The complete ICP 2 operating system — everything in one place',
    price: 997,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: [
      'Has multiple products but no system connecting them',
      'Inconsistent results without a repeatable process',
    ],
    problemSolved: 'Fragmented toolkit with no central system',
    transformation: 'From scattered tools → one complete creator operating system',
    shadowFears: ['SF5 — Invisible Labor', 'SF7 — Time Anxiety'],
    paidsStream: 'products',
    track: 'icp2-mid',
    description: 'Full ICP 2 system: niche + content + hooks + monetisation in one structured guide.',
    shopifyCopy: `Tools don\'t build businesses. Systems do.\n\nCreator Starter System is the complete ICP 2 operating system — niche, content calendar, hook framework, monetisation roadmap — built into one cohesive structure instead of scattered across 5 different guides.\n\nThe creator who finishes this guide has a business. Not a profile.\n\nR997. One system. The full picture.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'beginner',
    ladderPosition: 'core',
  },
  {
    code: 'P12',
    name: 'Hook Writing Masterclass',
    subtitle: 'The R×A×C×U^B formula mastered in a full workshop format',
    price: 997,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: ['Understands hooks conceptually but can\'t execute consistently'],
    problemSolved: 'Gap between knowing hook theory and writing hooks that actually perform',
    transformation: 'From inconsistent hooks → mastery of R×A×C×U^B with live examples',
    shadowFears: ['SF5 — Invisible Labor'],
    paidsStream: 'products',
    track: 'icp2-mid',
    description: 'Full workshop-format masterclass. R×A×C×U^B at full depth. 50 worked examples.',
    shopifyCopy: `The formula is R×A×C×U^B: Relevant × Awareness × Clarity × Unique to the power of Broad.\n\nIf any factor is zero, the hook fails. Every time.\n\nHook Writing Masterclass teaches the formula at full depth — not just the concept, but the execution. 50 worked examples across different niches and platforms. SA creator context throughout.\n\nR997. Full formula mastery. The scroll stops working for you.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'course',
    audienceLevel: 'established',
    ladderPosition: 'core',
  },
  {
    code: 'P13',
    name: '30-Day Consistency Blueprint',
    subtitle: 'Show up every day for 30 days — even when you don\'t want to',
    price: 497,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: ['Inconsistent posting', 'Starts strong, fades after week 2'],
    problemSolved: 'No consistency system for the real-world SA creator',
    transformation: 'From burst-and-stop → 30-day unbroken consistency streak',
    shadowFears: ['SF1 — Wasted Life', 'SF7 — Time Anxiety'],
    paidsStream: 'products',
    track: 'icp2-mid',
    description: 'Daily content habit architecture with load-shedding contingency and minimal viable content protocols.',
    shopifyCopy: `Consistency is not motivation. Motivation is a feeling. Consistency is a system.\n\nThe 30-Day Consistency Blueprint is not a challenge. It\'s a system — daily prompts, minimum viable content protocols for load-shedding days, and a weekly review that keeps you on track when life tries to knock you off it.\n\nR497. 30 days. Unbroken.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'beginner',
    ladderPosition: 'entry',
  },
  {
    code: 'P14',
    name: 'Story to Sale',
    subtitle: 'Turn your personal stories into content that builds trust and makes money',
    price: 997,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: ['Can\'t connect personal stories to sales', 'Doesn\'t know which stories to use or how'],
    problemSolved: 'No system for identifying and structuring stories that convert audiences to buyers',
    transformation: 'From stories that entertain → stories that sell without sounding like a pitch',
    shadowFears: ['SF3 — Imposter Syndrome', 'SF5 — Invisible Labor'],
    paidsStream: 'products',
    track: 'icp2-mid',
    description: 'Story identification, structure, and monetisation system. HSLFCTA framework applied to personal narrative.',
    shopifyCopy: `Every story you\'ve lived is a sales tool you haven\'t used yet.\n\nStory to Sale teaches you how to identify which stories from your life will resonate with your specific audience, how to structure them using the HSLFCTA formula, and how to end them with a CTA that doesn\'t break the emotional connection.\n\nThe stories are already yours. This guide teaches you how to use them.\n\nR997. Your stories. Your sales.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'established',
    ladderPosition: 'core',
  },
  {
    code: 'P15',
    name: 'PAIDS Monetisation Map',
    subtitle: 'The 5-stream income architecture for SA creators — map, activate, scale',
    price: 497,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: ['One income stream', 'Platform-dependent income', 'No plan for financial resilience'],
    problemSolved: 'Single stream income vulnerable to platform changes',
    transformation: 'From one income stream → 5-stream PAIDS architecture',
    shadowFears: ['SF6 — Platform Dependency', 'SF2 — Generational Poverty'],
    paidsStream: 'products',
    track: 'icp2-mid',
    description: 'PAIDS system (Products/Affiliates/Info/Deals/Services) fully mapped for ICP 2 with SA platforms and price points.',
    shopifyCopy: `Products. Affiliates. Information. Deals. Services.\n\nPAIDS is the 5-income-stream architecture that means when Meta cuts SA creators from the bonus programme — which it did, without warning — your business doesn\'t stop. Four other streams keep running.\n\nThe PAIDS Monetisation Map walks you through all 5 streams, the SA platforms for each, and the exact sequence to activate them.\n\nR497. Five streams. Income that survives the algorithm.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'established',
    ladderPosition: 'core',
  },
  {
    code: 'P16',
    name: 'Viral Script Kit',
    subtitle: '50 scripts across 5 content types — ready to film',
    price: 497,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: ['Doesn\'t know how to script videos', 'Goes off-script and loses viewers'],
    problemSolved: 'No template system for structured short-form video scripts',
    transformation: 'From unstructured content → 50 ready-to-film scripts across 5 content types',
    shadowFears: ['SF5 — Invisible Labor'],
    paidsStream: 'products',
    track: 'icp2-mid',
    description: '50 scripts across 5 types: tutorial, story, opinion, proof, framework. With 7-Act structure markers.',
    shopifyCopy: `The 10,500 reel was 200 words. Not improvised. Every word chosen.\n\nThe Viral Script Kit is 50 ready-to-film scripts across 5 content types — tutorial, story, opinion, proof, and framework reveal — each built on the 7-Act retention structure that keeps audiences watching to the end.\n\nFill in your niche. Film. Post.\n\nR497. 50 scripts. Film today.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'established',
    ladderPosition: 'core',
  },
  {
    code: 'P17',
    name: 'Niche Clarity Workbook',
    subtitle: 'The deep-dive niche workbook for creators who tried and failed before',
    price: 497,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: ['Tried a niche, it didn\'t work', 'Second-guessing their direction'],
    problemSolved: 'Niche indecision after failed first attempts',
    transformation: 'From niche regret → locked niche with 3-axis validation',
    shadowFears: ['SF4 — Wrong Path Terror'],
    paidsStream: 'products',
    track: 'icp2-mid',
    description: 'Deep workbook for second-time niche seekers. 3-Axis Check (Knowledge × Audience × Problem).',
    shopifyCopy: `You tried a niche. It didn\'t stick. Now you\'re wondering if you made the wrong choice.\n\nYou didn\'t make the wrong choice. You used the wrong process.\n\nThe Niche Clarity Workbook uses the 3-Axis Check — Knowledge × Audience × Problem — to lock in a niche that survives contact with reality. Not based on what\'s trending. Based on what you actually know, who actually needs it, and what SA audiences are already paying for.\n\nR497. Three axes. One locked niche.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'beginner',
    ladderPosition: 'core',
  },
  {
    code: 'P18',
    name: 'Zero to First R1,000',
    subtitle: 'Make your first R1,000 from content in 14 days — even with under 1,000 followers',
    price: 497,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: ['Never earned a rand from content', 'Thinks they need a big following to earn'],
    problemSolved: 'Belief that income requires a large following',
    transformation: 'From R0 to first R1,000 in 14 days using warm audience and MVP product',
    shadowFears: ['SF2 — Generational Poverty', 'SF3 — Imposter Syndrome'],
    paidsStream: 'products',
    track: 'icp2-mid',
    description: '14-day sprint with daily tasks. Warm audience outreach, MVP product, first Selar listing.',
    shopifyCopy: `The first R200 I made online, I was sitting in a car on a Sunday afternoon. I shook. Not because R200 is significant — because it was proof.\n\nZero to First R1,000 is a 14-day sprint guide for the creator who has never earned a rand from content and believes they need 10,000 followers first.\n\nYou don\'t. You need a system. This is the system.\n\nR497. 14 days. First R1,000.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'beginner',
    ladderPosition: 'entry',
  },
  {
    code: 'P19',
    name: '60-Second Script Templates',
    subtitle: '30 fill-in-the-blank scripts for the most important content format in SA',
    price: 297,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: ['Can\'t fill 60 seconds effectively', 'Rambles or runs out of content'],
    problemSolved: 'No template for the 60-second format that dominates SA short-form',
    transformation: 'From rambling 60-second videos → 30 structured templates with timing marks',
    shadowFears: ['SF5 — Invisible Labor'],
    paidsStream: 'products',
    track: 'icp2-mid',
    description: '30 fill-in-the-blank 60-second scripts with second-by-second timing marks.',
    shopifyCopy: `The 60-second format is the backbone of SA short-form content. It\'s long enough to teach something. Short enough to hold attention. Hard enough to fill without a template.\n\n60-Second Script Templates gives you 30 fill-in-the-blank scripts with second-by-second timing marks — so every second of your 60 is doing the job it\'s supposed to do.\n\nR297. 30 scripts. 60 seconds. Every one earns its time.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'beginner',
    ladderPosition: 'entry',
  },
  {
    code: 'P20',
    name: 'Brand Deal Pitch Pack',
    subtitle: 'The complete kit to land paid brand deals — pitch, rate card, and follow-up',
    price: 997,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: ['Waits for brands to come to them', 'Doesn\'t have a media kit or pitch'],
    problemSolved: 'No outbound brand deal system — waiting instead of pitching',
    transformation: 'From waiting for DMs → professional pitch system that generates inbound and outbound deals',
    shadowFears: ['SF3 — Imposter Syndrome', 'SF5 — Invisible Labor'],
    paidsStream: 'deals',
    track: 'icp2-mid',
    description: 'Media kit template, rate card calculator, outreach email sequence, follow-up scripts. SA brand list.',
    shopifyCopy: `Brands that pay big are not DMing random creators. They are being pitched by prepared ones.\n\nThe Brand Deal Pitch Pack is the complete outbound system: a media kit template, a rate card calculator (SA market rates), a cold outreach email sequence, and follow-up scripts for brands that go quiet.\n\nI pitched Samsung. Nike. Netflix. Not all found. But all pitched. The pitch pack was the difference between waiting and earning.\n\nR997. Full pitch system. Start pitching.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'established',
    ladderPosition: 'core',
  },
  {
    code: 'P21',
    name: 'Repurposing Playbook',
    subtitle: 'Turn 1 piece of content into 10 platform-specific posts — without reposting',
    price: 497,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: ['Creates new content every day instead of multiplying what works'],
    problemSolved: 'No repurposing system — treating every post as new work',
    transformation: 'From 1-and-done content → 10-post repurposing system per piece',
    shadowFears: ['SF7 — Time Anxiety', 'SF5 — Invisible Labor'],
    paidsStream: 'products',
    track: 'icp2-mid',
    description: '1-to-10 repurposing framework. Platform-specific adaptation for IG/TikTok/LinkedIn/YouTube. Decision tree.',
    shopifyCopy: `One video. Ten pieces of content. That\'s the math that makes content creation sustainable.\n\nThe Repurposing Playbook walks you through the exact framework for taking one strong piece of content and turning it into 10 platform-specific posts — without reposting the same thing and losing the SA creator credibility penalty that comes with lazy reposting.\n\nR497. One piece. Ten posts. Infinite leverage.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'established',
    ladderPosition: 'core',
  },

  // ─── ICP 1 TIER 3 ───────────────────────────────────────────
  {
    code: 'P22',
    name: 'Imposter Syndrome Fix',
    subtitle: 'Stop waiting for permission to share what you know — the expert\'s mindset reset',
    price: 997,
    icp: '1',
    icpLabel: 'ICP 1 — Called Expert (32–50)',
    painPoints: ['Knows their expertise but feels like a fraud sharing it publicly', 'Waiting until they\'re "ready"'],
    problemSolved: 'Imposter syndrome blocking experts from sharing and monetising their expertise',
    transformation: 'From "who am I to teach this" → clear expert identity with documented proof',
    shadowFears: ['SF3 — Imposter Syndrome', 'SF1 — Wasted Life'],
    paidsStream: 'products',
    track: 'icp1-tier3',
    description: '40-page mindset workbook with identity exercises. 3 identity statements. Proof archive. POSSESS activation.',
    shopifyCopy: `You have 15 years of expertise. You still hesitate before pressing post.\n\nThat hesitation is not humility. It is the belief that someone somewhere is more qualified to teach what only you have lived.\n\nImposter Syndrome Fix is a 40-page workbook that takes you through the POSSESS framework — 7 components of expert identity — and ends with 3 identity statements you will believe, because you\'ll have documented the proof yourself.\n\nR997. 7 components. Your expert identity locked.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'established',
    ladderPosition: 'entry',
  },
  {
    code: 'P23',
    name: 'MS×TS×SS Assessment',
    subtitle: 'Find the zero in your Mindset × Toolset × Skillset multiplication — then fix it',
    price: 997,
    icp: 'both',
    icpLabel: 'Both ICPs',
    painPoints: ['Stuck but doesn\'t know why', 'Has some things right but the result is still zero'],
    problemSolved: 'Unknown blocker preventing income growth',
    transformation: 'From "I don\'t know what\'s wrong" → specific zero identified and 30-day fix plan',
    shadowFears: ['SF4 — Wrong Path Terror', 'SF1 — Wasted Life'],
    paidsStream: 'products',
    track: 'icp2-mid',
    description: '20-question diagnostic. Identifies which factor is closest to zero. 30-day rebuild plan per result.',
    shopifyCopy: `Mindset × Toolset × Skillset = Creator Income.\n\nAny factor at zero makes the result zero. Always. No exceptions.\n\nThe MS×TS×SS Assessment is a 20-question diagnostic that identifies which factor is closest to zero in your specific situation — and ends with a 30-day rebuild plan calibrated to your result.\n\nYou don\'t need more information. You need the right diagnosis.\n\nR997. 20 questions. Your zero identified. Your rebuild starts.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'established',
    ladderPosition: 'core',
  },
  {
    code: 'P24',
    name: 'The Villain Framework',
    subtitle: 'Name the enemy in your content — the system villain that makes your message urgent',
    price: 997,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator (18–35)',
    painPoints: ['Content lacks urgency', 'Audience doesn\'t feel the stakes'],
    problemSolved: 'Content that educates but doesn\'t activate because there\'s no identified enemy',
    transformation: 'From informational content → narrative-driven content with a named villain that creates urgency',
    shadowFears: ['SF5 — Invisible Labor', 'SF6 — Platform Dependency'],
    paidsStream: 'products',
    track: 'icp2-mid',
    description: '30-page villain naming framework. 10 SA content villains. How to use them without being political or polarising.',
    shopifyCopy: `Every great story has a villain. Every great content piece names the enemy.\n\nNot a person — a system. Not a brand — a broken process. Not politics — a situation your audience already knows is wrong.\n\nThe Villain Framework teaches you how to name the enemy in your content — the thing that is actively costing your audience something — in a way that creates urgency, builds community, and converts viewers to buyers.\n\nR997. Name the villain. Activate the audience.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'established',
    ladderPosition: 'core',
  },
  {
    code: 'P25',
    name: 'Package Your Expertise',
    subtitle: 'Turn what you know into a sellable product — in 3 days',
    price: 1997,
    icp: '1',
    icpLabel: 'ICP 1 — Called Expert (32–50)',
    painPoints: ['Has expertise but no product', 'Gives advice for free or at hourly rates'],
    problemSolved: 'Expertise that isn\'t packaged into a sellable product',
    transformation: 'From "I give free advice" → a priced, structured product ready for Selar/Gumroad',
    shadowFears: ['SF2 — Generational Poverty', 'SF1 — Wasted Life'],
    paidsStream: 'products',
    track: 'icp1-tier3',
    description: '50-page professional product design guide. DARES test. ICP 1 pricing framework. 3-day build sprint.',
    shopifyCopy: `You are already qualified. You are not yet monetised. Those are different problems.\n\nPackage Your Expertise walks a professional through the process of taking existing expertise and building a sellable product in 3 days — not months. Not a course with 47 modules. A focused, priced product that solves one specific problem for one specific person.\n\nThe expertise is already yours. This guide turns it into income.\n\nR1,997. 3 days. Your expertise productised.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'core',
  },
  {
    code: 'P26',
    name: 'Authority Hook System',
    subtitle: 'Hooks for professionals — the framework for writing authority-first opening lines',
    price: 1497,
    icp: '1',
    icpLabel: 'ICP 1 — Called Expert (32–50)',
    painPoints: ['Tries entertainment hooks that don\'t match their professional persona'],
    problemSolved: 'Using entertainment hooks when their ICP responds to authority hooks',
    transformation: 'From mismatched hook style → authority-first openings that attract professional clients',
    shadowFears: ['SF3 — Imposter Syndrome', 'SF5 — Invisible Labor'],
    paidsStream: 'products',
    track: 'icp1-tier3',
    description: 'Authority hook framework with 50 ICP 1-specific hooks. Entertainment vs authority comparison.',
    shopifyCopy: `"Entertainment hooks attract views. Authority hooks attract clients."\n\nThe Authority Hook System teaches professionals how to write opening lines that signal credibility before they say the lesson — so their ICP (other professionals, business decision-makers) stops scrolling because they recognise the voice of someone who has done the work.\n\nIncludes 50 authority hooks across professional niches. SA-specific.\n\nR1,497. 50 hooks. Your clients start finding you.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'core',
  },
  {
    code: 'P27',
    name: 'First Digital Course',
    subtitle: 'Build and launch your first digital course in 21 days',
    price: 1997,
    icp: '1',
    icpLabel: 'ICP 1 — Called Expert (32–50)',
    painPoints: ['Wants to build a course but doesn\'t know where to start', 'Afraid of perfecting before launching'],
    problemSolved: 'No structured process for building and launching a first course',
    transformation: 'From course idea → launched, paid, reviewed course in 21 days',
    shadowFears: ['SF4 — Wrong Path Terror', 'SF7 — Time Anxiety'],
    paidsStream: 'products',
    track: 'icp1-tier3',
    description: '21-day course build sprint. Minimum viable course framework. SA platform options (Selar, Thinkific).',
    shopifyCopy: `A course that doesn\'t exist helps no one. A course that launches imperfect helps someone.\n\nFirst Digital Course is a 21-day build sprint guide — from course topic to live payment link — for the professional who has been planning a course for longer than they\'d like to admit.\n\nNot a lecture on course design. A step-by-step sprint that ends with a live product.\n\nR1,997. 21 days. Your first course live.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'core',
  },
  {
    code: 'P28',
    name: 'Contentpreneur OS',
    subtitle: 'The complete operating system for the creator building a serious content business',
    price: 3497,
    icp: 'both',
    icpLabel: 'Both ICPs — Advanced',
    painPoints: ['Has all the pieces but no system connecting them', 'Business feels chaotic and reactive'],
    problemSolved: 'No central operating system for the content business',
    transformation: 'From reactive content creation → a systemised content business with documented SOPs',
    shadowFears: ['SF1 — Wasted Life', 'SF6 — Platform Dependency'],
    paidsStream: 'products',
    track: 'icp1-tier3',
    description: 'Full content business OS: PAIDS + DARES + 4E + SEEDS + POSSESS in one interconnected system.',
    shopifyCopy: `The creator who runs a business is different from the creator who posts on social media.\n\nThe difference is the operating system.\n\nContentpreneur OS connects all six NOCHILL frameworks — PAIDS income architecture, DARES business model, 4E content strategy, SEEDS sales sequence, POSSESS identity, and MS×TS×SS personal audit — into one interconnected system with SOPs, templates, and a 90-day implementation roadmap.\n\nR3,497. One OS. A business, not a profile.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'course',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'premium',
  },
  {
    code: 'P29',
    name: 'Story Mining for Experts',
    subtitle: 'Excavate 20 years of professional stories — and turn them into content that converts',
    price: 1997,
    icp: '1',
    icpLabel: 'ICP 1 — Called Expert (32–50)',
    painPoints: ['Doesn\'t think their professional life has stories worth sharing', 'Can\'t connect career history to content'],
    problemSolved: 'Expertise not connected to story — content feels generic and impersonal',
    transformation: 'From "I don\'t have interesting stories" → 50-story bank from real professional life',
    shadowFears: ['SF5 — Invisible Labor', 'SF3 — Imposter Syndrome'],
    paidsStream: 'products',
    track: 'icp1-tier3',
    description: 'Decade Review system. Wound Library. 50-story bank with shadow fear and platform tags.',
    shopifyCopy: `Your career is full of stories that your future audience is waiting for.\n\nNot the curated LinkedIn success story. The moment you almost quit. The client who taught you everything by being impossible. The time the system failed you and you found a better way.\n\nStory Mining for Experts is a workbook that excavates 3 decades of professional life — using a structured Decade Review — and builds a 50-story bank tagged by shadow fear, platform, and content type.\n\nR1,997. Three decades excavated. 50 stories ready.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'core',
  },
  {
    code: 'P30',
    name: 'The Script System',
    subtitle: 'Long-form to short-form mastery — the 7-Act formula across all content lengths',
    price: 1997,
    icp: '1',
    icpLabel: 'ICP 1 — Called Expert (32–50)',
    painPoints: ['Loses viewers in the middle of long-form content', 'Can\'t compress long-form to short-form'],
    problemSolved: 'No cross-format script architecture for professional content creators',
    transformation: 'From single-format scripting → mastery across 15s/30s/60s/90s/5min+ formats',
    shadowFears: ['SF5 — Invisible Labor', 'SF3 — Imposter Syndrome'],
    paidsStream: 'products',
    track: 'icp1-tier3',
    description: '55-page advanced script guide. 7-Act at full depth. Authority vs Entertainment script comparison. 30-template Script Vault.',
    shopifyCopy: `A scripted professional sounds more authentic than one who improvises — because the script contains only truth. No filler. No hedging. No vague wisdom.\n\nThe Script System is the advanced guide for professionals who create content across multiple lengths and formats. The 7-Act retention formula applied to 15-second to 10-minute content, with second-precise timing templates and a 30-template Script Vault.\n\nThe authority vs entertainment script comparison alone is worth the price.\n\nR1,997. Full format mastery. Your expertise sounds like expertise.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'core',
  },

  // ─── ICP 1 TIER 4 ───────────────────────────────────────────
  {
    code: 'P31',
    name: 'LinkedIn Authority Builder',
    subtitle: 'Build a 40,000-follower LinkedIn presence — the 90-day authority roadmap',
    price: 1997,
    icp: '1',
    icpLabel: 'ICP 1 — Called Expert (32–50)',
    painPoints: ['No professional platform presence', 'LinkedIn profile is a CV not a magnet'],
    problemSolved: 'No LinkedIn authority strategy — missing the highest-converting ICP 1 platform',
    transformation: 'From invisible LinkedIn profile → inbound lead-generating authority presence',
    shadowFears: ['SF5 — Invisible Labor', 'SF1 — Wasted Life'],
    paidsStream: 'products',
    track: 'icp1-tier4',
    description: '50-page guide. POSSESS-driven profile rewrite. 4 post types. 90-day authority ramp. B2B pipeline.',
    shopifyCopy: `LinkedIn is the only platform where professional expertise converts directly to professional income.\n\nLinkedIn Authority Builder is a 50-page guide built for the professional who has never used LinkedIn as a content platform — covering the POSSESS-framework profile rewrite, 4 post types for authority positioning, the 90-day ramp from 0 to inbound leads, and the B2B pipeline that turns followers to clients.\n\n40,000 followers in 90 days is not the goal. Inbound client conversations are.\n\nR1,997. 90 days. Authority that pays.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'premium',
  },
  {
    code: 'P32',
    name: 'Monetise Your Expertise',
    subtitle: 'Build 3 active income streams from your expertise in 30 days',
    price: 2497,
    icp: '1',
    icpLabel: 'ICP 1 — Called Expert (32–50)',
    painPoints: ['Professional income but no passive or scalable income', 'One income stream, vulnerable'],
    problemSolved: 'Expertise with zero income architecture',
    transformation: 'From one income stream → 3 PAIDS streams in 30 days',
    shadowFears: ['SF2 — Generational Poverty', 'SF6 — Platform Dependency'],
    paidsStream: 'products',
    track: 'icp1-tier4',
    description: '45-page 4-week roadmap. Income audit. First product. First information offer. First sales (5-DM sequence).',
    shopifyCopy: `You are already qualified. You are not yet monetised. Those are different problems.\n\nMost professional development content solves the first. Monetise Your Expertise solves the second.\n\nA 4-week, 30-day roadmap: Week 1 income audit, Week 2 first product built, Week 3 first consulting offer designed, Week 4 first 3 sales made. By Day 30, 3 income streams active.\n\nR2,497. Four weeks. Three streams.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'premium',
  },
  {
    code: 'P33',
    name: 'Tax-Ready Creator',
    subtitle: 'SARS + digital income compliance for SA professionals earning online',
    price: 1497,
    icp: '1',
    icpLabel: 'ICP 1 — Called Expert (32–50)',
    painPoints: ['Earning significantly from digital sources but SARS-exposed', 'Doesn\'t know provisional tax obligations'],
    problemSolved: 'No SA-specific digital income tax compliance guide for professionals earning R5K+/month online',
    transformation: 'From SARS anxiety → full compliance structure with provisional tax filed',
    shadowFears: ['SF2 — Generational Poverty', 'SF4 — Wrong Path Terror'],
    paidsStream: 'products',
    track: 'icp1-tier4',
    description: '40-page handbook. Income classification. PAIDS tax treatment. Deductions. Provisional tax guide. 15-point checklist.',
    shopifyCopy: `SARS sent me a letter for R207,879. Not a fine — tax on income I legitimately earned but categorised incorrectly.\n\nTax-Ready Creator is the guide I wish existed in 2021: SA-specific digital income tax for professionals earning from brand deals, products, consulting, and coaching.\n\nCovers income classification, the PAIDS tax treatment for each stream, deductible SA creator expenses, and the provisional tax system — with a 15-point annual compliance checklist.\n\nNote: Educational guidance. Consult a registered tax practitioner.\n\nR1,497. SA-specific. SARS-ready.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'premium',
  },
  {
    code: 'P34',
    name: 'The Spiritual Creator',
    subtitle: 'Build a content business that aligns with your faith — not against it',
    price: 997,
    icp: 'both',
    icpLabel: 'Both ICPs — Faith-Led',
    painPoints: ['Feels creating for money contradicts faith', 'Spiritual dissonance with monetisation'],
    problemSolved: 'Belief that building a content business conflicts with Christian faith',
    transformation: 'From spiritual conflict around money → clarity that purpose-driven wealth is a calling',
    shadowFears: ['SF9 — Spiritual Crisis', 'SF4 — Wrong Path Terror'],
    paidsStream: 'products',
    track: 'icp1-tier3',
    description: '35-page guide. Deuteronomy 1:6 as the theological anchor. 5 faith-money integration principles.',
    shopifyCopy: `"His children\'s children should find what I built."\n\nThe Spiritual Creator is for the SA creator who loves God and is building something — but carries an unspoken tension between the two.\n\nBuilt on Deuteronomy 1:6 as the theological anchor, this guide walks through 5 principles for building a purpose-driven content business that is explicitly Christian in motivation and ruthlessly effective in execution.\n\nFor the 97% of SA creators who carry faith as part of their identity.\n\nR997. Faith and business. Not in conflict.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'established',
    ladderPosition: 'core',
  },
  {
    code: 'P35',
    name: 'NOCHILL Certification',
    subtitle: 'The official NOCHILL content creator certification — for creators serious about the standard',
    price: 3997,
    icp: '2',
    icpLabel: 'ICP 2 — Advanced Creator',
    painPoints: ['No credential to signal content professionalism', 'Wants to teach but lacks authority'],
    problemSolved: 'No credential that signals mastery of NOCHILL frameworks',
    transformation: 'From self-taught creator → NOCHILL-certified content professional',
    shadowFears: ['SF3 — Imposter Syndrome', 'SF1 — Wasted Life'],
    paidsStream: 'products',
    track: 'icp1-tier3',
    description: '12-week certification programme. Full NOCHILL curriculum assessed. Digital badge + certificate.',
    shopifyCopy: `The NOCHILL Content Creator Certification is not a course. It is an assessment.\n\nYou have 12 weeks to demonstrate mastery of the NOCHILL framework — PAIDS, 4E, SEEDS, POSSESS, MS×TS×SS, Section 13, and the 7-Act formula — through submitted deliverables reviewed by NOCHILL-certified assessors.\n\nPass. Receive the badge. Join the certified community.\n\nR3,997. 12 weeks. Certified.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'course',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'premium',
  },
  {
    code: 'P36',
    name: '90-Day Content Business Build',
    subtitle: 'From expert to income architecture — the 90-day guided programme',
    price: 7997,
    icp: '1',
    icpLabel: 'ICP 1 — High-Commitment',
    painPoints: ['Has the knowledge, not the execution', 'Needs structure and accountability'],
    problemSolved: 'Information without implementation — knowledge gap is gone, execution gap remains',
    transformation: 'From knowing what to do → 90 days of structured implementation with 6 binary deliverables by Day 90',
    shadowFears: ['SF4 — Wrong Path Terror', 'SF1 — Wasted Life'],
    paidsStream: 'products',
    track: 'icp1-tier4',
    description: '65-page programme guide + 12 weekly worksheets. Phase 1: Identity. Phase 2: Products. Phase 3: Activation.',
    shopifyCopy: `If you\'ve bought guides. If you\'ve read frameworks. If you\'ve understood the strategy but not executed — this is not a product. It is a programme.\n\nThe 90-Day Content Business Build is a 12-week structured implementation programme: 3 phases, 12 weekly guides, 12 worksheets, and 6 binary deliverables that tell you clearly whether you\'ve built what you\'re meant to build.\n\nBy Day 90: creator identity documented, first product live, first offer designed, first email sequence running, first 3 pitches sent.\n\nR7,997. 90 days. A content business, not a plan.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'course',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'premium',
  },
  {
    code: 'P37',
    name: 'Called Expert Accelerator',
    subtitle: '6-month high-touch coaching for professionals building from expertise',
    price: 25000,
    icp: '1',
    icpLabel: 'ICP 1 — Premium Coaching',
    painPoints: ['Professional with expertise and no content business', 'Tried self-study and stopped'],
    problemSolved: 'Implementation gap that self-study cannot close — requires accountability and personal coaching',
    transformation: 'From unmonetised expert → R20K-R50K/month digital income with full PAIDS architecture in 6 months',
    shadowFears: ['SF1 — Wasted Life', 'SF2 — Generational Poverty', 'SF3 — Imposter Syndrome'],
    paidsStream: 'info',
    track: 'icp1-tier4',
    description: 'Group coaching programme. Biweekly live calls. Private community. 6 modules over 24 weeks. Application-gated.',
    shopifyCopy: `You are called. That is the starting point.\n\nThe Called Expert Accelerator begins there — not with tactics, not with templates — but with the fact that you carry something others need.\n\nA 6-month group coaching programme: biweekly live calls, private community, resource vault (R15,000+ value), and direct feedback on your submissions.\n\n6 modules. 24 weeks. Identity → Products → Offers → Sales → Deals → Scale.\n\nApplication required. Not everyone is accepted.\n\nR25,000 once-off or R4,500 × 6 months.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'coaching',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'elite',
  },
  {
    code: 'P38',
    name: 'Strategy Session',
    subtitle: '90 minutes to clarity — one problem, one plan, one next step',
    price: 5000,
    icp: '1',
    icpLabel: 'ICP 1 — Consulting',
    painPoints: ['Knows something is wrong but can\'t identify the specific blocker'],
    problemSolved: 'Unidentified blocker preventing income growth',
    transformation: 'From confusion → one diagnosis, 7 specific actions, 30-day roadmap',
    shadowFears: ['SF4 — Wrong Path Terror', 'SF7 — Time Anxiety'],
    paidsStream: 'info',
    track: 'icp1-tier4',
    description: '90-minute live session + pre-session questionnaire + post-session roadmap. One diagnosis. Seven actions.',
    shopifyCopy: `90 minutes. One problem. One plan.\n\nThe 1-on-1 Strategy Session is not a coaching call. It is a diagnosis. In 90 minutes, you\'ll leave with: the root block identified, a 7-action plan specific to your situation, and a 30-day roadmap delivered in writing within 24 hours.\n\nFor the professional who has enough information and needs the right next step.\n\nR5,000. 90 minutes. Clarity.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'coaching',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'premium',
  },
  {
    code: 'P39',
    name: 'Launch Your First Digital Product',
    subtitle: 'Build and launch your first digital product in 14 days',
    price: 5000,
    icp: '1',
    icpLabel: 'ICP 1 — Launch Ready',
    painPoints: ['Has expertise, has draft file, hasn\'t published', 'Perfectionism blocking launch'],
    problemSolved: 'Launch paralysis — the product exists in draft form but never ships',
    transformation: 'From draft file on laptop → live Selar/Gumroad listing with first sale in 14 days',
    shadowFears: ['SF4 — Wrong Path Terror', 'SF7 — Time Anxiety'],
    paidsStream: 'products',
    track: 'icp1-tier4',
    description: '50-page 14-day guided launch sprint. Day-by-day tasks. Platform setup (Selar/Gumroad). 5-piece launch content.',
    shopifyCopy: `The first product I sold was 12 pages. I made R200 from it sitting in a car on a Sunday. The R200 wasn\'t from the 12 pages. It was from the act of publishing.\n\nLaunch Your First Digital Product is a 14-day guided sprint that takes you from draft file to live product. Daily tasks. Platform setup. 5-piece launch content. Day 14: your product is live and the first 20 DMs are sent.\n\nR5,000. 14 days. First product live.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'premium',
  },
  {
    code: 'P40',
    name: 'NOCHILL Licensing Programme',
    subtitle: 'Franchise NOCHILL frameworks — certified to deliver them to your own clients',
    price: 35000,
    priceRange: 'R35,000–R75,000',
    icp: '1',
    icpLabel: 'ICP 1 — Trainers & Consultants',
    painPoints: ['Wants to deliver NOCHILL methodology professionally', 'Needs formal IP rights'],
    problemSolved: 'No formal pathway to license and deliver NOCHILL frameworks',
    transformation: 'From informal framework user → certified NOCHILL licensed trainer with full IP rights',
    shadowFears: ['SF3 — Imposter Syndrome', 'SF5 — Invisible Labor'],
    paidsStream: 'deals',
    track: 'icp1-tier4',
    description: 'Application-gated licensing programme. Individual (R35K) and business (R75K) tiers. Full framework documentation + delivery tools.',
    shopifyCopy: `The NOCHILL Licensing Programme is not available on checkout. It begins with a conversation.\n\nFor trainers, coaches, and consultants who have been using NOCHILL frameworks informally and want to deliver them formally — with certification, full documentation, facilitation guides, and the legal right to use the IP.\n\nIndividual Licence: R35,000 | Business Licence (up to 5 trainers): R75,000.\n\nApplication required. Qualification criteria apply.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'service',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'elite',
  },
  {
    code: 'P41',
    name: 'PAIDS Framework',
    subtitle: 'The standalone PAIDS income architecture system — deep dive',
    price: 1997,
    icp: 'both',
    icpLabel: 'Both ICPs',
    painPoints: ['Single income stream', 'Platform dependency'],
    problemSolved: 'One-stream income vulnerability',
    transformation: 'From single stream → 5-stream PAIDS architecture at full depth',
    shadowFears: ['SF6 — Platform Dependency', 'SF2 — Generational Poverty'],
    paidsStream: 'products',
    track: 'framework',
    description: 'Standalone PAIDS guide. OTH→LL→MFM progression. All 5 streams at full depth for both ICPs.',
    shopifyCopy: `Products. Affiliates. Information. Deals. Services.\n\nThe PAIDS Framework is the standalone, deep-dive guide to the 5-income-stream architecture — for both content creators and professionals who want income that survives platform changes, algorithm updates, and market shifts.\n\nWhen one stream ends, the other four continue. That is the architecture.\n\nR1,997. Five streams. Full depth.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'core',
  },
  {
    code: 'P42',
    name: 'The DARES System',
    subtitle: 'Build a business that works without you — Digital, Automated, Recurring, Evergreen, Scalable',
    price: 1997,
    icp: 'both',
    icpLabel: 'Both ICPs',
    painPoints: ['Business stops when they stop working', 'Trading time for money'],
    problemSolved: 'Income that requires constant manual work to continue',
    transformation: 'From manual income → DARES-tested automated income architecture',
    shadowFears: ['SF6 — Platform Dependency', 'SF1 — Wasted Life'],
    paidsStream: 'products',
    track: 'framework',
    description: '40-page DARES framework. One section per criterion. SA platform examples. DARES audit worksheet.',
    shopifyCopy: `R600,000 in Meta Bonuses in 12 months. When Meta cut SA from the programme, that stream ended overnight.\n\nMy business survived — not because I was lucky, but because 4 other streams were already built on DARES principles: Digital, Automated, Recurring, Evergreen, Scalable.\n\nThe DARES System is the diagnostic guide for building income that doesn\'t stop when you do.\n\nR1,997. Five criteria. A business that works without you.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'core',
  },
  {
    code: 'P43',
    name: '4E Content System',
    subtitle: 'Educate. Entertain. Encourage. Earn. The 3:3:3:1 content strategy that grows and earns.',
    price: 1497,
    icp: '2',
    icpLabel: 'ICP 2 — Content Creator',
    painPoints: ['Posts one type of content repeatedly', 'Either grows OR earns — not both'],
    problemSolved: 'Wrong content ratio blocking growth or income',
    transformation: 'From single-type content → 3:3:3:1 balanced content diet that grows and converts',
    shadowFears: ['SF5 — Invisible Labor', 'SF6 — Platform Dependency'],
    paidsStream: 'products',
    track: 'framework',
    description: '35-page 4E guide. 10 prompts per E category (40 total). 3:3:3:1 content calendar template.',
    shopifyCopy: `Most creators are trying to grow an audience and wondering why they\'re not making money. Or making money from a launch and wondering why their audience is dropping.\n\nThe problem is not your content. The problem is your ratio.\n\nThe 4E Content System — Educate / Entertain / Encourage / Earn at 3:3:3:1 — is the content diet that builds audiences AND converts them. 40 post prompts across all 4 categories. Monthly calendar template.\n\nR1,497. Four categories. One ratio. Both goals achieved.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'established',
    ladderPosition: 'core',
  },
  {
    code: 'P44',
    name: 'SEEDS Sales Sequence',
    subtitle: 'Signal → Engagement → Education → Decision → Success. The automated sales system.',
    price: 1997,
    icp: 'both',
    icpLabel: 'Both ICPs',
    painPoints: ['Has products but no automated sales system', 'Sells manually with inconsistent results'],
    problemSolved: 'No automated email sequence converting subscribers to buyers',
    transformation: 'From manual selling → 11-email SEEDS sequence running 24/7',
    shadowFears: ['SF6 — Platform Dependency', 'SF5 — Invisible Labor'],
    paidsStream: 'products',
    track: 'framework',
    description: '38-page guide + 11 email templates. ICP 2 and ICP 1 versions. SA email platform guidance.',
    shopifyCopy: `A sequence is a salesperson who works while you sleep. Doesn\'t need a salary. Doesn\'t forget what to say. Doesn\'t get nervous before the close.\n\nThe SEEDS Sales Sequence is a 5-stage automated email system (Signal → Engagement → Education → Decision → Success) built for SA creators and professionals — with 11 fill-in templates, SA-specific objection handling, and platform setup guides for ConvertKit and Brevo.\n\nR1,997. 11 templates. Selling while you sleep.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'core',
  },
  {
    code: 'P46',
    name: 'MS×TS×SS Programme',
    subtitle: 'Mindset × Toolset × Skillset. Find your zero. Fix it. Change the result.',
    price: 1997,
    icp: 'both',
    icpLabel: 'Both ICPs',
    painPoints: ['Stuck without knowing which factor is the problem'],
    problemSolved: 'Unknown blocker in one of the three factors',
    transformation: 'From "I don\'t know what\'s wrong" → factor identified and 30-day rebuild plan',
    shadowFears: ['SF4 — Wrong Path Terror', 'SF1 — Wasted Life'],
    paidsStream: 'products',
    track: 'framework',
    description: '35-page guide + 20-question assessment. 30-day rebuild plan per zero type.',
    shopifyCopy: `Mindset × Toolset × Skillset = Creator Income. Any factor at zero: the result is zero.\n\nThe MS×TS×SS Programme is a 35-page deep dive into all three factors — with a 20-question self-assessment that identifies your zero and a 30-day rebuild plan calibrated to whether you\'re fixing mindset, toolset, or skillset.\n\nR1,997. Three factors audited. Your zero fixed.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'established',
    ladderPosition: 'core',
  },
  {
    code: 'P48',
    name: 'Section 13 Compliance',
    subtitle: 'The 15-point content quality standard — run before every post',
    price: 997,
    icp: 'both',
    icpLabel: 'Both ICPs',
    painPoints: ['Inconsistent content quality', 'Posts things they regret'],
    problemSolved: 'No quality standard applied to content before publishing',
    transformation: 'From inconsistent quality → professional publishing standard applied every time',
    shadowFears: ['SF5 — Invisible Labor', 'SF3 — Imposter Syndrome'],
    paidsStream: 'products',
    track: 'framework',
    description: '20-page reference guide + printable 15-point checklist. One page per check with definition, example, and fix.',
    shopifyCopy: `9 awards in 8 years. Not because I post more. Because I publish differently.\n\nSection 13 is the 15-point internal standard that runs behind every piece of content I produce — hook quality, ICP alignment, shadow fear activation, story presence, forbidden phrase audit, grammar, and 9 other checks.\n\nThis guide makes it external. Run it before you post. Every time.\n\nR997. 15 checks. Professional standard.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'established',
    ladderPosition: 'core',
  },
  {
    code: 'P49',
    name: 'Hook Formula System',
    subtitle: 'R×A×C×U^B mastered — 100-hook swipe file + formula deep dive',
    price: 1497,
    icp: '2',
    icpLabel: 'ICP 2 — Advanced Creator',
    painPoints: ['Inconsistent hook performance', 'Occasional viral but mostly low-reach'],
    problemSolved: 'No systematic hook engineering process',
    transformation: 'From hook guessing → R×A×C×U^B mastered with 100 formula-passing hooks',
    shadowFears: ['SF5 — Invisible Labor'],
    paidsStream: 'products',
    track: 'framework',
    description: '30-page formula guide + 100-hook swipe file (80 ICP2 + 20 ICP1). R×A×C×U^B at full depth.',
    shopifyCopy: `Same week. Same creator. Same niche. One reel: 47 views. One reel: 2.3 million views.\n\nThe difference was the hook. 8 words in the opening.\n\nThe Hook Formula System teaches R×A×C×U^B at full depth — Relevant × Awareness × Clarity × Unique^Broadened — and includes a 100-hook swipe file where every entry passes the formula before it was included.\n\nR1,497. One formula. 100 examples. The scroll stops.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'established',
    ladderPosition: 'core',
  },
  {
    code: 'P50',
    name: '7-Act Retention Formula',
    subtitle: 'Make them watch until the end — the psychological architecture of high-retention content',
    price: 1497,
    icp: '2',
    icpLabel: 'ICP 2 — Video Creator',
    painPoints: ['Loses 60-70% of audience by second 15', 'High impressions, low completion rate'],
    problemSolved: 'No narrative architecture for short-form content',
    transformation: 'From 30% completion rates → content that holds 70%+ through the 7-act structure',
    shadowFears: ['SF5 — Invisible Labor'],
    paidsStream: 'products',
    track: 'framework',
    description: '35-page guide + 10 fill-in-the-blank 60-second scripts. 7 acts at full depth with timing marks.',
    shopifyCopy: `Every story that has ever held human attention follows the same pattern. Hook → Contract → Pattern Interrupt → Story → Lesson → Callback → CTA.\n\nThe 7-Act Retention Formula teaches this architecture for short-form video — second by second. The retention cliff is at second 15. Most creators don\'t know it\'s there. This guide teaches you how to interrupt it.\n\nIncludes 10 fill-in-the-blank 60-second scripts across 10 content types.\n\nR1,497. 7 acts. Audiences that stay.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'digital_product',
    audienceLevel: 'established',
    ladderPosition: 'core',
  },

  // ─── BUNDLES ────────────────────────────────────────────────
  {
    code: 'B1',
    name: 'Creator Starter Bundle',
    subtitle: 'Everything a new SA creator needs to begin — 3 products, one price',
    price: 349,
    icp: '2',
    icpLabel: 'ICP 2 — New Creators',
    painPoints: ['Doesn\'t know where to start', 'Multiple purchase decisions at once'],
    problemSolved: 'Entry barrier for new creators needing multiple tools at once',
    transformation: 'From scattered start → 3 tools working together with a 30-day roadmap',
    shadowFears: ['SF4 — Wrong Path Terror', 'SF7 — Time Anxiety'],
    paidsStream: 'products',
    track: 'bundle',
    description: 'P05 (Checklist) + P04 (Idea System) + P06 (Caption Pack) + Welcome Guide. Value: R1,091.',
    shopifyCopy: `The Creator Starter Bundle is the 3 tools every new SA creator needs before posting another piece of content.\n\n✓ The Broke Creator Checklist — know exactly where your system is broken\n✓ No Content Ideas — 90-day idea bank from 3 inputs\n✓ Caption Formula Pack — 10 formulas, 50 templates\n✓ 30-Day Starter Welcome Guide (exclusive to bundle)\n\nTotal value: R1,091 | Bundle price: R349.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'bundle',
    audienceLevel: 'beginner',
    ladderPosition: 'entry',
    isBundle: true,
  },
  {
    code: 'B2',
    name: 'Monetisation Bundle',
    subtitle: 'From audience to income — 3 tools for the SA creator ready to earn',
    price: 499,
    icp: '2',
    icpLabel: 'ICP 2 — Audience Builders',
    painPoints: ['Has audience, no income system'],
    problemSolved: 'Gap between having an audience and having income',
    transformation: 'From audience to first R200 earned in 30 days',
    shadowFears: ['SF2 — Generational Poverty', 'SF6 — Platform Dependency'],
    paidsStream: 'products',
    track: 'bundle',
    description: 'P07 (Brand Deal Script) + P15 (PAIDS Map) + P18 (Zero to R1K) + Welcome Guide. Value: R1,291.',
    shopifyCopy: `The Monetisation Bundle is the 3-tool system for the SA creator who has an audience and hasn\'t made money from it yet.\n\n✓ PAIDS Monetisation Map — identify your highest-priority income stream\n✓ First Brand Deal Script — 5 scripts for every brand DM scenario\n✓ Zero to First R1,000 — 14-day monetisation sprint\n✓ 30-Day Monetisation Welcome Guide (exclusive)\n\nTotal value: R1,291 | Bundle price: R499.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'bundle',
    audienceLevel: 'beginner',
    ladderPosition: 'entry',
    isBundle: true,
  },
  {
    code: 'B3',
    name: 'ICP 1 Foundation Bundle',
    subtitle: 'The 4-guide foundation sequence for the professional building a content business',
    price: 3997,
    icp: '1',
    icpLabel: 'ICP 1 — Professional Experts',
    painPoints: ['Needs complete ICP 1 onboarding, not single tools'],
    problemSolved: 'Fragmented ICP 1 entry — no sequential onboarding',
    transformation: 'From professional with no content presence → identity, stories, product, and LinkedIn in 60 days',
    shadowFears: ['SF3 — Imposter Syndrome', 'SF1 — Wasted Life'],
    paidsStream: 'products',
    track: 'bundle',
    description: 'P22 (Imposter Fix) + P25 (Package Expertise) + P29 (Story Mining) + P31 (LinkedIn) + 60-Day Guide. Value: R6,988.',
    shopifyCopy: `The ICP 1 Foundation Bundle is the 60-day onboarding sequence for the professional who is ready to begin.\n\n✓ Imposter Syndrome Fix — creator identity locked\n✓ Package Your Expertise — first product built\n✓ Story Mining for Experts — 50 professional stories excavated\n✓ LinkedIn Authority Builder — inbound platform built\n✓ 60-Day Foundation Guide (exclusive to bundle)\n\nTotal value: R6,988 | Bundle price: R3,997.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'bundle',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'premium',
    isBundle: true,
  },
  {
    code: 'B4',
    name: 'Full Framework Bundle',
    subtitle: 'Six frameworks. One system. No gaps in your content business.',
    price: 7997,
    icp: 'both',
    icpLabel: 'Both ICPs — Advanced',
    painPoints: ['Has some frameworks, missing others', 'Wants the complete NOCHILL system'],
    problemSolved: 'Incomplete framework toolkit',
    transformation: 'From partial framework usage → complete 6-framework OS',
    shadowFears: ['SF6 — Platform Dependency', 'SF4 — Wrong Path Terror'],
    paidsStream: 'products',
    track: 'bundle',
    description: 'P41 (PAIDS) + P42 (DARES) + P43 (4E) + P44 (SEEDS) + P46 (MS×TS×SS) + P48 (Section 13) + Master Reference Guide. Value: R10,482.',
    shopifyCopy: `Six NOCHILL frameworks. One complete operating system.\n\n✓ PAIDS Framework — income architecture\n✓ DARES System — business model validation\n✓ 4E Content System — content strategy\n✓ SEEDS Sales Sequence — automated selling\n✓ MS×TS×SS Programme — personal effectiveness audit\n✓ Section 13 Compliance — quality standard\n✓ Master Framework Reference Guide (exclusive)\n\nTotal value: R10,482 | Bundle price: R7,997.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'bundle',
    audienceLevel: 'contentpreneur',
    ladderPosition: 'elite',
    isBundle: true,
  },
  {
    code: 'B5',
    name: 'Content Creator OS Bundle',
    subtitle: 'Plan it. Write it. Post it consistently. Get more from every piece.',
    price: 997,
    icp: '2',
    icpLabel: 'ICP 2 — Systematisers',
    painPoints: ['Chaotic content workflow', 'Creates in bursts with no system'],
    problemSolved: 'No operating system for the daily content workflow',
    transformation: 'From chaotic creation → 4-component creator OS running in 4 weeks',
    shadowFears: ['SF7 — Time Anxiety', 'SF5 — Invisible Labor'],
    paidsStream: 'products',
    track: 'bundle',
    description: 'P03 (Calendar) + P21 (Repurpose) + P13 (Consistency) + P16 (Scripts) + OS Install Guide. Value: R1,788.',
    shopifyCopy: `The Content Creator OS Bundle installs 4 components of a complete content operating system.\n\n✓ Content Calendar System — plan 30 days in one afternoon\n✓ Repurposing Playbook — 1 piece becomes 10 platform posts\n✓ 30-Day Consistency Blueprint — never miss a week\n✓ Viral Script Kit — 50 scripts ready to film\n✓ Creator OS Installation Guide (exclusive)\n\nWhen all four are running: content creation takes 2 hours per day.\n\nTotal value: R1,788 | Bundle price: R997.\n\ncontentcreatorhub.online | @nochill_god`,
    productType: 'bundle',
    audienceLevel: 'established',
    ladderPosition: 'core',
    isBundle: true,
  },
]

export const TRACK_LABELS: Record<ProductTrack, string> = {
  'icp2-entry': 'ICP 2 — Entry',
  'icp2-mid': 'ICP 2 — Mid Tier',
  'icp1-tier3': 'ICP 1 — Tier 3',
  'icp1-tier4': 'ICP 1 — Tier 4',
  'framework': 'Standalone Framework',
  'bundle': 'Bundle',
}

export const STATUS_CONFIG = {
  draft: { label: 'Draft', color: 'text-[#8A8071]', bg: 'bg-[#E8E1D0]', border: 'border-[#DED5C2]' },
  building: { label: 'Building', color: 'text-[#7A5F18]', bg: 'bg-[#C9A646]/15', border: 'border-[#C9A646]/40' },
  built: { label: 'Built', color: 'text-emerald-700', bg: 'bg-emerald-50', border: 'border-emerald-200' },
  live: { label: 'Live', color: 'text-blue-700', bg: 'bg-blue-50', border: 'border-blue-200' },
}
